name: Build Image

on:
  pull_request: {}
  push:
    branches:
      github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt install coreutils p7zip-full qemu-user-static
    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/guysoft/CustomPiOS.git'
    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/bitbyt3r/v1pi.git'
    - name: Download Raspbian Image
      run: cd v1pi/src/image && wget -q -c --trust-server-names 'https://downloads.raspberrypi.org/raspbian_lite_latest'
    - name: Update CustomPiOS Paths
      run: cd v1pi/src && ../../CustomPiOS/src/update-custompios-paths
    - name: Build v1pi Image
      run: sudo modprobe loop && cd v1pi/src && sudo bash -x ./build_dist
    - name: Move Output
      run: mv /home/runner/work/v1pi/v1pi/v1pi/src/workspace/*-raspbian-buster-lite.img v1pi.img
    - name: Zip Output
      run: gzip v1pi.img
    - uses: actions/upload-artifact@v1
      with:
        name: v1pi.img.gz
        path: v1pi.img.gz
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload Release
      id: upload-release-asset-fullpageos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: v1pi.img.gz
        asset_name: v1pi.img.gz
        asset_content_type: application/octet-stream